# Generated by Django 4.2 on 2023-05-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_ticketref_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='magniture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
