# Generated by Django 4.2 on 2023-05-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cardNumber', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('exp', models.CharField(max_length=4)),
            ],
        ),
    ]
