# Generated by Django 4.2 on 2023-05-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='exp',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket')),
            ],
        ),
    ]
